name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan setiap tengah malam
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Chandra13July
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg?palette=github-dark"
          push: true
